<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var dmstr\news\models\Video $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="video-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'enableClientValidation' => false]); ?>

    <div class="">
        <?php echo $form->errorSummary($model); ?>
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= // generated by dmstr\news\providers\RelationProvider::activeField
$form->field($model, 'video_gallery_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(dmstr\news\models\VideoGallery::find()->all(),'id','name'),
    ['prompt'=>'Choose...']
); ?>
			<?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>
			<?= $form->field($model, 'youtube_url')->textInput(['maxlength' => 255]) ?>
			<?= $form->field($model, 'published_at')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'Video',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?= Html::submitButton(
                        '<span class="glyphicon glyphicon-check"></span> ' . ($model->isNewRecord
                                    ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
                        ['class' => 'btn btn-primary']
            );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
